import { dirname, join, resolve } from 'node:path';
import { mkdir, readFile, rename, writeFile } from 'node:fs/promises';
import { EvidenceDecisionLedgerV2, SourceOfTruthRegistryV2, PromptInjectionDefenseV2, GitHubEngineeringEngineV2, RepositoryAuditorV2, CiCdVerificationEngineV2, GoogleIntelligenceV2, McpOrchestrationFabricV2, AndroidEngineeringEngineV2, AgentEngineeringEngineV2, CloudInfrastructureEngineV2, SystemArchitectureEngineV2, OMNI_V22_COMPETENCY_MAP } from './omni-architecture.mjs';
async function readJson(path,fallback){try{return JSON.parse(await readFile(path,'utf8'));}catch(e){if(e?.code==='ENOENT')return structuredClone(fallback);throw e;}}
async function writeJsonAtomic(path,value){await mkdir(dirname(path),{recursive:true});const tmp=`${path}.${process.pid}.${Date.now()}.tmp`;await writeFile(tmp,JSON.stringify(value,null,2)+'\n','utf8');await rename(tmp,path);}
export class OmniCompetencyRuntime {
  constructor({root,repositoryInspect=null,ciRunner=null,deviceRunner=null,mcpInvoker=null,realityGate=null}={}){if(!root)throw new Error('root is required');this.root=resolve(root);this.repositoryInspect=repositoryInspect;this.ciRunner=ciRunner;this.deviceRunner=deviceRunner;this.mcpInvoker=mcpInvoker;this.realityGate=realityGate;this.ledger=new EvidenceDecisionLedgerV2();this.sourceTruth=new SourceOfTruthRegistryV2();this.injection=new PromptInjectionDefenseV2();this.github=new GitHubEngineeringEngineV2();this.repoAuditor=new RepositoryAuditorV2();this.cicd=new CiCdVerificationEngineV2();this.google=new GoogleIntelligenceV2({injection:this.injection});this.mcp=new McpOrchestrationFabricV2();this.android=new AndroidEngineeringEngineV2();this.agents=new AgentEngineeringEngineV2();this.cloud=new CloudInfrastructureEngineV2();this.architecture=new SystemArchitectureEngineV2();this.statePath=join(this.root,'.omega','omni-v22.json');}
  async action({action,payload={}}={}){switch(action){case 'competency-map':return structuredClone(OMNI_V22_COMPETENCY_MAP);case 'evidence-add':return this.ledger.addEvidence(payload);case 'decision-add':return this.ledger.addDecision(payload);case 'ledger-snapshot':return this.ledger.snapshot();case 'source-upsert':return this.sourceTruth.upsert(payload);case 'source-resolve':return this.sourceTruth.resolve(payload.domain);case 'injection-screen':return this.injection.audit(payload);case 'github-plan':return this.github.plan(payload);case 'repo-audit':return this.repoAuditor.audit(payload);case 'repo-live-inspect':return await this.#repoLive(payload);case 'ci-verify':return this.cicd.verify(payload);case 'ci-live':return await this.#ciLive(payload);case 'google-ingest':return this.google.ingest(payload);case 'google-query':return this.google.query(payload);case 'mcp-register':return this.mcp.register(payload);case 'mcp-route':return this.mcp.route(payload);case 'mcp-live-call':return await this.#mcpLive(payload);case 'android-gate':return this.android.gate(payload);case 'android-live':return await this.#androidLive(payload);case 'agent-spec':return this.agents.spec(payload);case 'agent-evaluate':return this.agents.evaluate(payload);case 'cloud-gate':return this.cloud.gate(payload);case 'adr-add':return this.architecture.addAdr(payload);case 'adr-list':return this.architecture.list();case 'quality-gate':return await this.#qualityGate(payload);case 'state-save':return await this.#save();case 'state-load':return await this.#load();default:throw new Error(`Unsupported Omni v22 action: ${action}`);}}
  async #repoLive(payload){if(!this.repositoryInspect)return {available:false,reason:'REPOSITORY_INSPECTOR_UNAVAILABLE'};return {available:true,result:await this.repositoryInspect({cwd:payload.cwd??this.root})};}
  async #ciLive(payload){if(!this.ciRunner)return {available:false,reason:'CI_RUNNER_UNAVAILABLE'};return {available:true,result:await this.ciRunner(payload)};}
  async #androidLive(payload){if(!this.deviceRunner)return {available:false,reason:'DEVICE_RUNNER_UNAVAILABLE'};return {available:true,result:await this.deviceRunner(payload)};}
  async #mcpLive({capability,arguments:args={},write=false}={}){const route=this.mcp.route({capability,write});if(!route.selected)return {executed:false,reason:'NO_AUTHORIZED_PROVIDER',route};if(!this.mcpInvoker)return {executed:false,reason:'MCP_INVOKER_UNAVAILABLE',route};const result=await this.mcpInvoker({providerId:route.selected.id,name:capability,arguments:args});return {executed:true,route,result};}
  async #qualityGate(payload={}){const base={ledger:this.ledger.snapshot(),sourceTruth:this.sourceTruth.snapshot(),...payload};if(!this.realityGate)return {passed:false,reason:'REALITY_GATE_UNAVAILABLE',input:base};const result=await this.realityGate(base);return {passed:Boolean(result?.passed??result?.allowed??false),result};}
  async #save(){const state={version:22,ledger:this.ledger.snapshot(),sourceTruth:this.sourceTruth.snapshot(),google:this.google.snapshot(),mcp:this.mcp.snapshot(),adrs:this.architecture.list(),savedAt:new Date().toISOString()};await writeJsonAtomic(this.statePath,state);return {saved:true,path:this.statePath,version:22};}
  async #load(){const state=await readJson(this.statePath,{version:22});this.ledger.restore(state.ledger??{});this.sourceTruth.restore(state.sourceTruth??[]);this.google.restore(state.google??[]);this.mcp.restore(state.mcp??[]);this.architecture.restore(state.adrs??[]);return {loaded:true,version:state.version??22};}
}
