import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync,existsSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {parseProjectIssue,parseDesign,verifyScaffold,agentProject,publishReview} from '../scripts/omega-project-agent.mjs';
import {scaffold} from '../scripts/omega-project-factory.mjs';
const event={repository:{full_name:'mojealterego/Agent-God-Level-Omega',owner:{login:'mojealterego'}},issue:{number:44,user:{login:'mojealterego'},title:'[THOR-PROJECT] web omega-web',body:'mobile-first tasks dashboard'}};
test('allows only owner issue in trusted repository',()=>{assert.equal(parseProjectIssue(event).kind,'web');assert.throws(()=>parseProjectIssue({...event,issue:{...event.issue,user:{login:'other'}}}),/UNAUTHORIZED/);assert.throws(()=>parseProjectIssue({...event,issue:{...event.issue,title:'[THOR-PROJECT] web ../evil'}}),/KIND_AND_SLUG/)});
test('metadata parser forbids unexpected code/path fields',()=>{assert.equal(parseDesign('{"title":"OMEGA Studio","description":"Ready","accent":"#ff0088"}',parseProjectIssue(event)).accent,'#ff0088');assert.throws(()=>parseDesign('{"title":"x","path":"../../"}',parseProjectIssue(event)),/UNEXPECTED_FIELDS/)});
test('generated web project actually executes the test runner',()=>{const root=mkdtempSync(join(tmpdir(),'omega-agent-smoke-'));try{const artifact=scaffold({kind:'web',slug:'omega-web'},{out:join(root,'project')});const ok=verifyScaffold({kind:'web'},artifact);assert.equal(ok.pass,true,ok.log);assert.equal(ok.status,'TESTED')}finally{rmSync(root,{recursive:true,force:true})}});
test('native Android source is not misrepresented as a compiled APK',()=>{const root=mkdtempSync(join(tmpdir(),'omega-agent-native-'));try{const artifact=scaffold({kind:'android',slug:'native-game'},{out:join(root,'project')});const ok=verifyScaffold({kind:'android'},artifact);assert.equal(ok.pass,true);assert.equal(ok.apkVerified,false);assert.match(ok.status,/APK_UNVERIFIED/)}finally{rmSync(root,{recursive:true,force:true})}});
test('three model-backed stages generate a verified web scaffold',async()=>{
 const root=mkdtempSync(join(tmpdir(),'omega-agent-three-'));let num=0;try{const result=await agentProject(event,{base:root,env:{GITHUB_RUN_ID:'22'},tokenProvider:async()=> 'jwt',fetchImpl:async(_url,req)=>{num++;const {agentRole}=JSON.parse(req.body);const content=agentRole==='implementer'?'{"title":"OMEGA Studio","description":"Personal project dashboard","accent":"#38bdf8"}': 'Verified summary of task acceptance with no fabrication.';return{ok:true,status:200,text:async()=>JSON.stringify({ok:true,role:agentRole,provider:'lovable-ai',content})}}});assert.equal(num,3);assert.equal(result.verified.pass,true);assert(existsSync(join(result.artifact.target,'index.html')));assert.equal(result.receipt.modelCalls,3);assert.equal(result.receipt.merged,false)}finally{rmSync(root,{recursive:true,force:true})}
});
test('publication stops immediately after an unsuccessful command',async()=>{const counts=[];await assert.rejects(publishReview({issue:{number:1},verified:{pass:true},receipt:{sourceRoot:'a'},spec:{kind:'web'}},{runner:(bin,args)=>{counts.push(bin);return{status:1,stderr:'denied'}}}),/PUBLISH_FAILED/);assert.equal(counts.length,1)});
