substitutions:
  _REGION: us-central1
  _REPOSITORY: omega
  _IMAGE: app
  _SERVICE: app
steps:
- name: gcr.io/cloud-builders/docker
  args: ['build','-t','${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$COMMIT_SHA','.']
- name: gcr.io/cloud-builders/docker
  args: ['push','${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$COMMIT_SHA']
- name: gcr.io/google.com/cloudsdktool/cloud-sdk
  entrypoint: gcloud
  args: ['run','deploy','${_SERVICE}','--image','${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$COMMIT_SHA','--region','${_REGION}','--platform','managed','--quiet']
images:
- '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_IMAGE}:$COMMIT_SHA'
