import {mkdir,readFile,rename,writeFile} from 'node:fs/promises';
import {dirname,join,resolve,sep} from 'node:path';
const ROLES=new Set(['IDENTITY_SOURCE','FACE_SOURCE','BODY_SOURCE','POSE_SOURCE','COMPOSITION_SOURCE','CAMERA_SOURCE','ENVIRONMENT_SOURCE','BACKGROUND_SOURCE','WARDROBE_SOURCE','MATERIAL_SOURCE','LIGHTING_SOURCE','COLOR_SOURCE','TYPOGRAPHY_SOURCE','STYLE_SOURCE','DETAIL_SOURCE']);
const B={MICRO:0,LOCAL:1,REGIONAL:2,GLOBAL:3,CREATIVE_REBUILD:4};
const CK=['intentFidelity','referenceFidelity','identityIntegrity','subjectCount','editScope','composition','anatomy','kinesiology','perspective','lighting','materials','color','compositing','text','photorealism','noUnrequestedChanges','noReferenceContamination','requestedChangeApplied','environment','style'];
const cp=v=>structuredClone(v), uniq=(v=[])=>[...new Set(v.map(x=>String(x).trim()).filter(Boolean))], now=()=>new Date().toISOString();
function need(v,n){v=String(v??'').trim();if(!v)throw new Error(n+' is required');return v}
function status(s,score=null,evidence=null,note=null){return{status:s,score,evidence,note}}
function blankValidation(){return{status:'UNCHECKED',checks:Object.fromEntries(CK.map(k=>[k,status('UNCHECKED')]))}}
function obs(v,fn,score=null,evidence=null,note=null){return v==null?status('INCONCLUSIVE',score,evidence,note):status(fn(v)?'PASS':'FAIL',score??(typeof v==='number'?v:null),evidence,note)}
function all(c){const s=Object.values(c).map(x=>x.status);return s.includes('FAIL')?'FAIL':s.every(x=>x==='PASS')?'PASS':'INCONCLUSIVE'}
async function atomic(path,value){await mkdir(dirname(path),{recursive:true});const t=path+'.tmp';await writeFile(t,JSON.stringify(value,null,2)+'\n');await rename(t,path)}
export class WdaVisualRuntime{
 constructor({root,providerInvoker=null,commandRunner=null,clock=now}={}){if(!root)throw new Error('root is required');this.root=resolve(root);this.providerInvoker=providerInvoker;this.commandRunner=commandRunner;this.clock=clock;this.sessions=new Map;this.statePath=join(this.root,'.omega','wda-visual-state.json')}
 async action({action,payload={}}={}){const a={
  'session-create':()=>this.create(payload),'state-get':()=>cp(this.get(payload.sessionId)),'reference-add':()=>this.refAdd(payload),'reference-role-set':()=>this.refSet(payload),'reference-map':()=>this.refMap(this.get(payload.sessionId)),'intent-compile':()=>this.intent(payload),'state-transition':()=>this.transition(payload),'lock-set':()=>this.lock(payload),'change-budget':()=>this.budget(payload),'edit-plan':()=>this.edit(payload),'mask-plan':()=>this.mask(payload),'provider-compile':()=>this.compile(payload),'provider-execute':()=>this.execute(payload),'composite-execute':()=>this.composite(payload),'compare':()=>this.compare(payload),'validate':()=>this.validate(payload),'failure-classify':()=>this.failures(payload),'correction-apply':()=>this.correct(payload),'snapshot':()=>this.snapshot(payload),'state-save':()=>this.save(),'state-load':()=>this.load(payload)}[action];if(!a)throw new Error('Unsupported WDA visual action: '+action);return await a()}
 inside(p){const x=resolve(this.root,String(p??''));if(x!==this.root&&!x.startsWith(this.root+sep))throw new Error('Path escapes workspace: '+p);return x}
 get(id){id=need(id,'sessionId');const s=this.sessions.get(id);if(!s)throw new Error('Unknown WDA session: '+id);return s}
 touch(s){s.updatedAt=this.clock()}
 budgetOk(x){if(!(x in B))throw new Error('Unsupported change budget: '+x)}
 create({id,rawRequest='',expectedSubjectCount=null,changeBudget='LOCAL',metadata={}}={}){id=need(id,'session id');this.budgetOk(changeBudget);if(expectedSubjectCount!=null&&(!Number.isInteger(expectedSubjectCount)||expectedSubjectCount<0))throw new Error('expectedSubjectCount must be a non-negative integer or null');const t=this.clock(),s={system:'WDA_OMEGA_INFINITY',version:'1.0.0',id,intent:{rawRequest:String(rawRequest),normalizedIntent:null,primaryGoal:null,secondaryGoals:[],creativeBoundary:'preserve unspecified visual state'},references:[],referenceGraph:{authoritative:{},conflicts:[]},visualState:{source:null,locked:[],flexible:[],modified:[],removed:[],added:[],derived:[]},subject:{expectedCount:expectedSubjectCount,identityLock:false},pose:{},attire:{},composition:{},environment:{},lighting:{},camera:{},materials:{},colorScience:{},realism:{},compositing:{},typography:{enabled:false,exactText:null},negativeConstraints:{identity:[],subjectCount:[],anatomy:[],composition:[],environment:[],wardrobe:[],materials:[],rendering:[],text:[],unrequestedChanges:[]},changeControl:{changeBudget,editScope:null,immutableElements:[],secondaryChangesAllowed:[],globalRegeneration:false,mask:null},attention:{critical:[],high:[],medium:[],low:[]},validation:blankValidation(),editPlans:[],providerExecutions:[],corrections:[],snapshots:[],metadata:cp(metadata),createdAt:t,updatedAt:t};this.sessions.set(id,s);return cp(s)}
 roles(v=[]){const a=uniq(v);for(const r of a)if(!ROLES.has(r))throw new Error('Unsupported reference role: '+r);return a}
 refAdd({sessionId,reference}={}){const s=this.get(sessionId),id=need(reference?.id,'reference.id');if(s.references.some(x=>x.id===id))throw new Error('Reference already exists: '+id);const r={id,source:need(reference.source,'reference.source'),roles:this.roles(reference.roles),priority:Number(reference.priority??0),metadata:cp(reference.metadata??{})};s.references.push(r);s.referenceGraph=this.refMap(s);this.touch(s);return cp(r)}
 refSet({sessionId,referenceId,roles,priority}={}){const s=this.get(sessionId),r=s.references.find(x=>x.id===referenceId);if(!r)throw new Error('Unknown reference: '+referenceId);r.roles=this.roles(roles);if(priority!==undefined)r.priority=Number(priority);s.referenceGraph=this.refMap(s);this.touch(s);return cp(r)}
 refMap(s){const by={};for(const r of s.references)for(const role of r.roles)(by[role]??=[]).push(r);const authoritative={},conflicts=[];for(const[role,refs]of Object.entries(by)){refs.sort((a,b)=>b.priority-a.priority||a.id.localeCompare(b.id));const top=refs[0],ties=refs.filter(x=>x.priority===top.priority);authoritative[role]=ties.length===1?top.id:null;if(refs.length>1)conflicts.push({role,candidates:refs.map(x=>({id:x.id,priority:x.priority})),resolvedTo:authoritative[role],status:ties.length===1?'RESOLVED_BY_PRIORITY':'AMBIGUOUS_PRESERVE'})}return{authoritative,conflicts,resolutionStrategy:'highest explicit priority; ties remain unresolved'}}
 intent(p={}){const s=this.get(p.sessionId);for(const k of['normalizedIntent','primaryGoal','creativeBoundary'])if(p[k]!==undefined)s.intent[k]=p[k];if(p.secondaryGoals)s.intent.secondaryGoals=uniq(p.secondaryGoals);if(p.typographyEnabled!==undefined)s.typography.enabled=!!p.typographyEnabled;if(p.exactText!==undefined){s.typography.exactText=String(p.exactText);s.typography.enabled=true}for(const k of['subject','pose','attire','composition','environment','lighting','camera','materials','colorScience','realism','compositing','output'])if(p[k]!==undefined)s[k]={...(s[k]??{}),...cp(p[k])};this.touch(s);return cp(s)}
 disjoint(v){const l=new Set(v.locked);for(const k of['modified','removed','added'])for(const x of v[k])if(l.has(x))throw new Error('Visual state conflict: '+x+' is LOCKED')}
 transition(p={}){const s=this.get(p.sessionId),v=cp(s.visualState);if(p.source!==undefined)v.source=cp(p.source);for(const k of['locked','flexible','modified','removed','added','derived'])if(p[k]!==undefined)v[k]=uniq(p[k]);this.disjoint(v);s.visualState=v;s.subject.identityLock=v.locked.includes('identity');s.changeControl.immutableElements=uniq([...s.changeControl.immutableElements,...v.locked]);s.changeControl.secondaryChangesAllowed=uniq(v.derived);this.touch(s);return cp(s)}
 lock({sessionId,elements=[],mode='replace'}={}){const s=this.get(sessionId);s.visualState.locked=mode==='merge'?uniq([...s.visualState.locked,...elements]):uniq(elements);this.disjoint(s.visualState);s.changeControl.immutableElements=cp(s.visualState.locked);this.touch(s);return cp(s)}
 budget({sessionId,changeBudget}={}){const s=this.get(sessionId);this.budgetOk(changeBudget);s.changeControl.changeBudget=changeBudget;s.changeControl.globalRegeneration=B[changeBudget]>=B.GLOBAL;this.touch(s);return cp(s.changeControl)}
 edit({sessionId,scope='LOCAL',modified=[],removed=[],added=[],derived=[],preserve=[]}={}){const s=this.get(sessionId);this.budgetOk(scope);if(B[scope]>B[s.changeControl.changeBudget])throw new Error('Requested scope '+scope+' exceeds change budget '+s.changeControl.changeBudget);const plan={scope,modified:uniq(modified),removed:uniq(removed),added:uniq(added),derived:uniq(derived),immutableElements:uniq(preserve),globalRegeneration:B[scope]>=B.GLOBAL};s.editPlans.push(plan);s.changeControl.editScope=scope;s.changeControl.globalRegeneration=plan.globalRegeneration;s.changeControl.immutableElements=plan.immutableElements;this.touch(s);return cp(plan)}
 mask({sessionId,regions=[],semantics='white=editable, black=preserve'}={}){const s=this.get(sessionId);s.changeControl.mask={regions:cp(regions),semantics,required:B[s.changeControl.changeBudget]<=B.REGIONAL};this.touch(s);return cp(s.changeControl.mask)}
 compile({sessionId,provider='generic',mode='edit',model=null}={}){const s=this.get(sessionId),g=this.refMap(s);const locks='LOCKED: '+(s.visualState.locked.join(', ')||'none'),mods='MODIFIED: '+(s.visualState.modified.join(', ')||'none'),refs=Object.entries(g.authoritative).map(([r,id])=>r+'='+(id??'UNRESOLVED'));const q=['WDA OMEGA INFINITY','INTENT: '+(s.intent.normalizedIntent??s.intent.rawRequest),refs.length?'REFERENCE ROLES: '+refs.join('; '):'REFERENCE ROLES: none',locks,mods,'CHANGE BUDGET: '+s.changeControl.changeBudget,'EXPECTED SUBJECT COUNT: '+(s.subject.expectedCount??'UNSPECIFIED')];for(const[k,v]of[['POSE SPEC',s.pose],['ATTIRE SPEC',s.attire],['COMPOSITION SPEC',s.composition],['ENVIRONMENT SPEC',s.environment],['LIGHTING SPEC',s.lighting],['CAMERA SPEC',s.camera],['MATERIALS SPEC',s.materials],['COLOR SCIENCE SPEC',s.colorScience],['REALISM SPEC',s.realism],['COMPOSITING SPEC',s.compositing],['OUTPUT SPEC',s.output]])if(v&&Object.keys(v).length)q.push(k+': '+JSON.stringify(v));if(s.typography.enabled&&s.typography.exactText!=null)q.push('EXACT TEXT: '+s.typography.exactText);if(provider==='gemini')q.push('GEMINI REFERENCE MAPPING: '+s.references.flatMap(r=>r.roles.map(role=>r.id+' supplies '+role+' only')).join('; '));if(provider==='openai')q.push('OPENAI ADAPTATION: preserve unrelated pixels and regions; use edit mask when supplied.');q.push('Do not invent unknown visual facts; preserve unspecified state.');return{provider,model,action:mode==='generate'?'generate':'edit',instruction:q.join('\n'),references:cp(s.references),referenceGraph:cp(g),mask:cp(s.changeControl.mask),expectedSubjectCount:s.subject.expectedCount,deterministicGenerationClaimed:false}}
 async execute({sessionId,provider='generic',mode='edit',model=null,providerId,toolName,arguments:args={},approved=false}={}){if(approved!==true)throw new Error('approved=true is required for provider execution');if(typeof this.providerInvoker!=='function')throw new Error('No visual provider invoker is configured');const compiled=this.compile({sessionId,provider,mode,model}),request={providerId:need(providerId,'providerId'),name:need(toolName,'toolName'),arguments:{...cp(args),wda:compiled}},result=await this.providerInvoker(request),s=this.get(sessionId);s.providerExecutions.push({provider,providerId,toolName,observedAt:this.clock()});return{executed:true,request,result}}
 async composite({sessionId,sourcePath,generatedPath,maskPath,outputPath,magick='magick'}={}){const s=this.get(sessionId);if(typeof this.commandRunner!=='function')return{executed:false,available:false,reason:'NO_COMMAND_RUNNER'};const src=this.inside(need(sourcePath,'sourcePath')),gen=this.inside(need(generatedPath,'generatedPath')),mask=this.inside(need(maskPath,'maskPath')),out=this.inside(need(outputPath,'outputPath'));await mkdir(dirname(out),{recursive:true});const argv=[magick,src,gen,mask,'-compose','over','-composite',out],result=await this.commandRunner({argv,cwd:this.root,sideEffect:'L',timeoutMs:300000,maxOutputBytes:1048576}),executed=result?.exitCode===0;s.changeControl.mask={source:mask,semantics:'white=editable, black=preserve',postGenerationEnforced:executed};return{executed,available:true,engine:'ImageMagick',sourcePath:src,generatedPath:gen,maskPath:mask,outputPath:out,result}}
 compare({sessionId,observations={}}={}){const s=this.get(sessionId);return{expected:{subjectCount:s.subject.expectedCount,locked:cp(s.visualState.locked),modified:cp(s.visualState.modified),exactText:s.typography.enabled?s.typography.exactText:null},observed:cp(observations),claimsDeterministicIdentity:false}}
 validate({sessionId,observations:o={},thresholds={}}={}){const s=this.get(sessionId),t={identity:.9,reference:.85,anatomy:.85,kinesiology:.85,perspective:.85,lighting:.85,materials:.85,color:.85,compositing:.85,photorealism:.85,composition:.85,style:.8,lockedRegionChangeRatio:.01,...thresholds},c={};c.intentFidelity=obs(o.intentFidelityScore,v=>v>=.9);c.referenceFidelity=obs(o.referenceFidelityScore,v=>v>=t.reference);c.identityIntegrity=obs(o.identitySimilarity,v=>v>=t.identity,o.identitySimilarity,null,'similarity is not proof of identity');c.subjectCount=s.subject.expectedCount==null?status('INCONCLUSIVE'):obs(o.subjectCount,v=>v===s.subject.expectedCount);c.editScope=obs(o.lockedRegionChangeRatio,v=>v<=t.lockedRegionChangeRatio);for(const[k,key]of[['composition','compositionScore'],['anatomy','anatomyScore'],['kinesiology','kinesiologyScore'],['perspective','perspectiveScore'],['lighting','lightingScore'],['materials','materialsScore'],['color','colorScore'],['compositing','compositingScore'],['photorealism','photorealismScore'],['style','styleScore']])c[k]=obs(o[key],v=>v>=t[k]);c.text=obs(o.textExact,v=>v===true);c.noUnrequestedChanges=obs(o.noUnrequestedChanges,v=>v===true);c.noReferenceContamination=obs(o.noReferenceContamination,v=>v===true);c.requestedChangeApplied=obs(o.requestedChangeApplied,v=>v===true);c.environment=obs(o.environmentScore,v=>v>=.85);const r={status:all(c),checks:c,thresholds:t,observations:cp(o),validatedAt:this.clock(),unobservedTruthClaimed:false};s.validation=r;return cp(r)}
 failures({sessionId}={}){const s=this.get(sessionId),c=s.validation.checks??{},m={identityIntegrity:['F1','IDENTITY_DRIFT'],referenceFidelity:['F2','REFERENCE_CONTAMINATION'],noReferenceContamination:['F2','REFERENCE_CONTAMINATION'],subjectCount:['F3','SUBJECT_COUNT_ERROR'],environment:['F4','BACKGROUND_ERROR'],composition:['F5','COMPOSITION_DRIFT'],anatomy:['F6','ANATOMICAL_FAILURE'],kinesiology:['F6','ANATOMICAL_FAILURE'],lighting:['F7','LIGHTING_FAILURE'],materials:['F8','MATERIAL_FAILURE'],perspective:['F9','OPTICAL_FAILURE'],style:['F10','STYLE_FAILURE'],text:['F11','TEXT_FAILURE'],editScope:['F12','OVER_EDIT'],noUnrequestedChanges:['F12','OVER_EDIT'],requestedChangeApplied:['F13','UNDER_EDIT']},seen=new Set,failures=[];for(const[k,[code,label]]of Object.entries(m))if(c[k]?.status==='FAIL'&&!seen.has(code)){seen.add(code);failures.push({code,label,sourceCheck:k})}return{sessionId:s.id,failures,validationStatus:s.validation.status}}
 correct({sessionId,domain,correction,preserve=[]}={}){const s=this.get(sessionId);domain=need(domain,'domain');s.visualState.locked=uniq([...s.visualState.locked,...preserve]);if(s.visualState.locked.includes(domain))throw new Error('Correction domain is locked: '+domain);s.visualState.modified=uniq([...s.visualState.modified,domain]);s.corrections.push({domain,correction:need(correction,'correction'),preserve:uniq(preserve),at:this.clock()});s.validation=blankValidation();return cp(s)}
 snapshot({sessionId,label=null}={}){const s=this.get(sessionId),x={id:'snapshot-'+(s.snapshots.length+1),label,at:this.clock(),state:{intent:cp(s.intent),referenceGraph:cp(s.referenceGraph),visualState:cp(s.visualState),changeControl:cp(s.changeControl),validation:cp(s.validation)}};s.snapshots.push(x);return cp(x)}
 async save(){const x={version:1,sessions:Object.fromEntries([...this.sessions].map(([id,s])=>[id,cp(s)])),savedAt:this.clock()};await atomic(this.statePath,x);return{saved:true,path:this.statePath,sessionCount:this.sessions.size}}
 async load({state=null}={}){const x=state??JSON.parse(await readFile(this.statePath,'utf8'));if(!x?.sessions)throw new Error('Invalid WDA state payload');this.sessions=new Map(Object.entries(x.sessions).map(([id,s])=>[id,cp(s)]));return{loaded:true,sessionCount:this.sessions.size}}
}
export const WDA_REFERENCE_ROLES=Object.freeze([...ROLES]);
export const WDA_CHANGE_BUDGETS=Object.freeze(Object.keys(B));
