import test from 'node:test';
import assert from 'node:assert/strict';
import {
  AgentDirectory, ThorOrchestrator, LokiMarketIntel, KratosSecurity, RagnarAutomationScout,
  FlokiCatalog, AtreusDeviceSupervisor, ArtifactFactory
} from '../src/asgard/asgard-architecture.mjs';

test('agent directory preserves original six primary agents',()=>{const d=new AgentDirectory();const p=d.list({includeDomain:false});assert.deepEqual(p.slice(0,6).map(x=>x.id),['thor','loki','kratos','ragnar','floki','atreus']);assert.ok(p.length>=6);});
test('agents are grouped into categories',()=>{const d=new AgentDirectory();const cats=d.categories();assert.ok(cats.find(x=>x.category==='ANDROID').agents.includes('android-engineer'));assert.ok(cats.find(x=>x.category==='SECURITY').agents.includes('kratos'));});
test('agent lookup works by display name',()=>{const d=new AgentDirectory();assert.equal(d.card('Thor').id,'thor');assert.equal(d.card('Atreus').category,'DEVICE');});
test('Thor infers capabilities and delegates to domain agents',()=>{const t=new ThorOrchestrator();const task=t.submit({goal:'Zbuduj plugin MCP dla aplikacji Android z monetyzacją i testami'});assert.ok(task.capabilities.includes('plugin-build'));assert.ok(task.capabilities.includes('mcp-build'));assert.ok(task.subtasks.some(x=>x.agent==='android-engineer'));assert.ok(task.subtasks.some(x=>x.agent==='monetization-engineer'));});
test('Thor always adds QA gate',()=>{const t=new ThorOrchestrator();const task=t.submit({goal:'zbuduj skill'});assert.ok(task.subtasks.some(x=>x.capability==='quality-gate'&&x.agent==='qa-release-engineer'));});
test('Thor cannot finalize before required subtasks complete',()=>{const t=new ThorOrchestrator();const task=t.submit({goal:'zbuduj skill'});assert.equal(t.finalize(task.id).done,false);});
test('Thor finalizes only with all subtasks done',()=>{const t=new ThorOrchestrator();const task=t.submit({goal:'zbuduj skill'});for(const s of task.subtasks)t.update(task.id,{subtaskId:s.id,status:'DONE',evidence:['e'],artifacts:['a']});const out=t.finalize(task.id,{summary:'done',product:{kind:'skill'}});assert.equal(out.done,true);assert.deepEqual(out.task.final.artifacts,['a']);});
test('Loki ranks opportunities by evidence scores',()=>{const l=new LokiMarketIntel();l.ingest({title:'A',scores:{demand:1,competition:.1,monetization:.9,buildability:.8,strategicFit:.8}});l.ingest({title:'B',scores:{demand:.3,competition:.9,monetization:.2,buildability:.3,strategicFit:.3}});assert.equal(l.ranked()[0].title,'A');});
test('Loki handoff marks record for Thor',()=>{const l=new LokiMarketIntel();const r=l.ingest({title:'A'});assert.equal(l.handoff(r.id).status,'HANDED_TO_THOR');});
test('Kratos stores references instead of raw secrets',()=>{const k=new KratosSecurity();const r=k.registerSecretRef({id:'github',provider:'github',envRef:'GITHUB_TOKEN'});assert.equal(r.envRef,'GITHUB_TOKEN');assert.equal('value' in r,false);});
test('Kratos flags raw secret-like objects',()=>{const k=new KratosSecurity();assert.equal(k.rejectRawSecretObject({api_key:'1234567890SECRET'}).safe,false);assert.equal(k.rejectRawSecretObject({api_key:'env:OPENAI_API_KEY'}).safe,true);});
test('Kratos signing profile requires env references',()=>{const k=new KratosSecurity();const p=k.registerSigningProfile({keystorePathRef:'/safe/release.jks',alias:'upload',passwordEnv:'PLAY_STORE_PASS'});assert.equal(p.passwordEnv,'PLAY_STORE_PASS');});
test('Ragnar detects newly installed or discovered items',()=>{const r=new RagnarAutomationScout();r.snapshot({apps:['a'],providers:['p1']});const x=r.snapshot({apps:['a','b'],providers:['p1','p2']});assert.deepEqual(x.diff.newApps,['b']);assert.deepEqual(x.diff.newProviders,['p2']);});
test('Ragnar identifies automation gaps',()=>{const r=new RagnarAutomationScout();r.coverageSet({id:'a',automated:true,coverage:1});r.coverageSet({id:'b',automated:false,coverage:.2});assert.deepEqual(r.gaps(['a','b']).map(x=>x.id),['b']);});
test('Floki indexes records by category',()=>{const f=new FlokiCatalog();f.record({category:'MCP',item:'gateway'});f.record({category:'ANDROID',item:'builder'});assert.equal(f.catalog({category:'MCP'}).length,1);assert.equal(f.summary().total,2);});
test('Atreus health reports device issues',()=>{const a=new AtreusDeviceSupervisor();const h=a.interpretHealth({adbState:'offline',batteryLevel:10,freeBytes:1,totalBytes:100,developerOptions:false,adbEnabled:false});assert.equal(h.ok,false);assert.ok(h.issues.includes('LOW_STORAGE'));});
test('Atreus developer option changes require allowlist and approval',()=>{const a=new AtreusDeviceSupervisor();assert.equal(a.devOptionPlan({name:'window_animation_scale',value:0,approved:false}).reason,'APPROVAL_REQUIRED');assert.equal(a.devOptionPlan({name:'secure_random_setting',value:1,approved:true}).reason,'OPTION_NOT_ALLOWLISTED');assert.equal(a.devOptionPlan({name:'window_animation_scale',value:0,approved:true}).allowed,true);});
test('artifact factory supports requested artifact families',()=>{const f=new ArtifactFactory();for(const type of ['skill','mcp','plugin','tool','code-agent','no-code-agent','agent-system'])assert.equal(f.createSpec({type,name:`Test ${type}`}).type,type);});
