import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { AsgardRuntime } from '../src/asgard/asgard-runtime.mjs';

test('LISTA AGENTÓW v17 exposes ten primary agents',async()=>{const root=await mkdtemp(join(tmpdir(),'asgard16-'));try{const r=new AsgardRuntime({root});const out=await r.action({action:'command',payload:{text:'LISTA AGENTÓW'}});assert.equal(out.primary.length,10);assert.ok(out.primary.some(x=>x.id==='wieszcz'));}finally{await rm(root,{recursive:true,force:true});}});

test('Thor creates GitHub repo through gh when FULL automation is enabled',async()=>{const root=await mkdtemp(join(tmpdir(),'asgard16-'));try{const calls=[];const r=new AsgardRuntime({root,commandRunner:async c=>{calls.push(c);return {exitCode:0,stdout:JSON.stringify({html_url:'https://github.com/me/new-repo',full_name:'me/new-repo'}),stderr:''};}});await r.action({action:'thor-automation-mode',payload:{mode:'FULL'}});const out=await r.action({action:'thor-github-create-repo',payload:{name:'new-repo',visibility:'private'}});assert.equal(out.created,true);assert.equal(out.provider,'gh');assert.equal(calls[0].argv[0],'gh');}finally{await rm(root,{recursive:true,force:true});}});

test('Thor repo creation is gated in GUARDED mode without approval',async()=>{const root=await mkdtemp(join(tmpdir(),'asgard16-'));try{const r=new AsgardRuntime({root,commandRunner:async()=>{throw new Error('should not run');}});const out=await r.action({action:'thor-github-create-repo',payload:{name:'x'}});assert.equal(out.created,false);assert.equal(out.reason,'APPROVAL_OR_FULL_AUTOMATION_REQUIRED');}finally{await rm(root,{recursive:true,force:true});}});

test('Harald MCP connector pulls evidence through injected provider and can hand project to Thor',async()=>{const root=await mkdtemp(join(tmpdir(),'asgard16-'));try{const r=new AsgardRuntime({root,mcpInvoker:async req=>({items:[{id:'1',title:'New AI cloud grant',text:'credits for Android agent startup'}],request:req})});await r.action({action:'harald-connector-register',payload:{id:'mail',service:'GMAIL',transport:'MCP_FEDERATION',providerId:'gmail',toolName:'scan_ai',authorized:true}});const pull=await r.action({action:'harald-pull',payload:{connectorId:'mail',arguments:{days:7}}});assert.equal(pull.available,true);const projects=await r.action({action:'harald-projects'});assert.ok(projects.length);const hand=await r.action({action:'harald-to-thor',payload:{id:projects[0].id}});assert.match(hand.thorTask.goal,/Harald/i);}finally{await rm(root,{recursive:true,force:true});}});

test('Ivar dispatches project to both configured research providers without VPN claim',async()=>{const root=await mkdtemp(join(tmpdir(),'asgard16-'));try{const seen=[];const r=new AsgardRuntime({root,mcpInvoker:async req=>{seen.push(req);return {answer:`result:${req.providerId}`};}});await r.action({action:'ivar-provider-register',payload:{id:'chatgpt',kind:'CHATGPT',transport:'MCP_FEDERATION',providerId:'cg',toolName:'deep_research',authorized:true}});await r.action({action:'ivar-provider-register',payload:{id:'gemini',kind:'GEMINI',transport:'MCP_FEDERATION',providerId:'gm',toolName:'deep_research',authorized:true}});const p=await r.action({action:'ivar-project-create',payload:{title:'X',brief:'research X'}});const d=await r.action({action:'ivar-dispatch',payload:{id:p.id}});assert.equal(d.jobs.length,2);assert.equal(d.vpnClaimed,false);assert.equal(seen.length,2);}finally{await rm(root,{recursive:true,force:true});}});

test('Kronikarz writes article JSON and requests a PDF renderer when available',async()=>{const root=await mkdtemp(join(tmpdir(),'asgard16-'));try{const calls=[];const r=new AsgardRuntime({root,artifactScript:'/pkg/runtime/practical_artifacts.py',commandRunner:async c=>{calls.push(c);return {exitCode:0,stdout:JSON.stringify({ok:true,kind:'pdf',output:join(root,'reports/news.pdf')}),stderr:''};}});await r.action({action:'floki-record',payload:{category:'AI',item:'v17',notes:'done'}});const out=await r.action({action:'kronikarz-pdf',payload:{output:'reports/news.pdf',from:'2026-09-28',to:'2026-10-05'}});assert.equal(out.generated,true);assert.equal(calls[0].argv[0],process.env.OMEGA_PYTHON??'python3');const article=JSON.parse(await readFile(out.articlePath,'utf8'));assert.equal(article.brand,'Mojealterego News');}finally{await rm(root,{recursive:true,force:true});}});

test('Wieszcz exports marketplace catalog and payment intent remains external',async()=>{const root=await mkdtemp(join(tmpdir(),'asgard16-'));try{const r=new AsgardRuntime({root});await r.action({action:'wieszcz-benchmark-set',payload:{category:'BOOK',median:100,currency:'PLN'}});await r.action({action:'wieszcz-offer-upsert',payload:{id:'book',category:'BOOK',title:'Book',basePrice:80}});const exp=await r.action({action:'wieszcz-export-catalog',payload:{output:'market/catalog.json'}});assert.equal(exp.exported,true);const pay=await r.action({action:'wieszcz-payment-intent',payload:{orderId:'x',provider:'PAYPAL',amount:100,currency:'PLN'}});assert.equal(pay.executed,false);assert.equal(pay.externalProviderRequired,true);}finally{await rm(root,{recursive:true,force:true});}});

test('v17 state persists Harald Ivar Wieszcz and automation mode',async()=>{const root=await mkdtemp(join(tmpdir(),'asgard16-'));try{const r=new AsgardRuntime({root});await r.action({action:'thor-automation-mode',payload:{mode:'FULL'}});await r.action({action:'harald-connector-register',payload:{id:'g',service:'GITHUB',transport:'HOST_CONNECTOR',authorized:true}});await r.action({action:'ivar-provider-register',payload:{id:'chatgpt',kind:'CHATGPT',transport:'HOST_ORCHESTRATION',authorized:true}});await r.action({action:'wieszcz-offer-upsert',payload:{id:'a',category:'AI_AGENT',title:'A',basePrice:100}});const s=await r.action({action:'state-save'});assert.equal(s.version,20);const r2=new AsgardRuntime({root});const l=await r2.action({action:'state-load'});assert.equal(l.version,20);assert.equal((await r2.action({action:'thor-automation-get'})).mode,'FULL');assert.equal((await r2.action({action:'harald-connectors'})).length,1);assert.equal((await r2.action({action:'wieszcz-offers'})).length,1);}finally{await rm(root,{recursive:true,force:true});}});
