import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm, readFile, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { AsgardRuntime } from '../src/asgard/asgard-runtime.mjs';

test('LISTA AGENTÓW returns primary directory and categories',async()=>{const root=await mkdtemp(join(tmpdir(),'asgard-'));try{const r=new AsgardRuntime({root});const out=await r.action({action:'command',payload:{text:'LISTA AGENTÓW'}});assert.ok(out.primary.length>=6);assert.ok(out.categories.some(x=>x.category==='GAMES'));}finally{await rm(root,{recursive:true,force:true});}});
test('direct agent invocation selects Loki',async()=>{const root=await mkdtemp(join(tmpdir(),'asgard-'));try{const r=new AsgardRuntime({root});const out=await r.action({action:'invoke-agent',payload:{name:'Loki'}});assert.equal(out.activeAgent,'loki');assert.equal(out.separateModelClaimed,false);}finally{await rm(root,{recursive:true,force:true});}});
test('Thor factory creates a real skill package',async()=>{const root=await mkdtemp(join(tmpdir(),'asgard-'));try{const r=new AsgardRuntime({root});const out=await r.action({action:'factory-create',payload:{type:'skill',name:'Market Scout',description:'research',destination:'generated/market-scout'}});assert.equal(out.complete,true);const body=await readFile(join(root,'generated/market-scout/SKILL.md'),'utf8');assert.match(body,/Market Scout/);}finally{await rm(root,{recursive:true,force:true});}});
test('Thor factory creates MCP scaffold',async()=>{const root=await mkdtemp(join(tmpdir(),'asgard-'));try{const r=new AsgardRuntime({root});const out=await r.action({action:'factory-create',payload:{type:'mcp',name:'Test MCP'}});assert.ok(out.files.some(x=>x.path.endsWith('src/server.mjs')));}finally{await rm(root,{recursive:true,force:true});}});
test('factory cannot escape workspace',async()=>{const root=await mkdtemp(join(tmpdir(),'asgard-'));try{const r=new AsgardRuntime({root});await assert.rejects(()=>r.action({action:'factory-create',payload:{type:'skill',name:'x',destination:'../../escape'}}),/outside/);}finally{await rm(root,{recursive:true,force:true});}});
test('Loki opportunity can become Thor task',async()=>{const root=await mkdtemp(join(tmpdir(),'asgard-'));try{const r=new AsgardRuntime({root});const opp=await r.action({action:'loki-ingest',payload:{title:'AI Android niche',problem:'gap',scores:{demand:.9,competition:.2,monetization:.8,buildability:.8,strategicFit:1}}});const out=await r.action({action:'loki-to-thor',payload:{id:opp.id}});assert.equal(out.opportunity.status,'HANDED_TO_THOR');assert.match(out.thorTask.goal,/AI Android niche/);}finally{await rm(root,{recursive:true,force:true});}});
test('Kratos signing refuses without approval',async()=>{const root=await mkdtemp(join(tmpdir(),'asgard-'));try{const r=new AsgardRuntime({root});assert.equal((await r.action({action:'kratos-sign-apk',payload:{input:'x.apk'}})).reason,'APPROVAL_REQUIRED');}finally{await rm(root,{recursive:true,force:true});}});
test('Kratos signing doctor is fail-closed when tools unavailable',async()=>{const root=await mkdtemp(join(tmpdir(),'asgard-'));try{const r=new AsgardRuntime({root,commandRunner:async c=>{const e=new Error('missing');e.code='ENOENT';throw e;}});const out=await r.action({action:'kratos-signing-doctor'});assert.equal(out.ready,false);}finally{await rm(root,{recursive:true,force:true});}});
test('Ragnar parses live installed packages',async()=>{const root=await mkdtemp(join(tmpdir(),'asgard-'));try{const r=new AsgardRuntime({root,commandRunner:async()=>({exitCode:0,stdout:'package:b\npackage:a\n',stderr:''})});const out=await r.action({action:'ragnar-live-packages'});assert.deepEqual(out.apps,['a','b']);}finally{await rm(root,{recursive:true,force:true});}});
test('Atreus doctor interprets adb battery storage and developer options',async()=>{const root=await mkdtemp(join(tmpdir(),'asgard-'));try{const runner=async c=>{const s=c.argv.join(' ');if(s==='adb get-state')return {exitCode:0,stdout:'device\n'};if(s.includes('dumpsys battery'))return {exitCode:0,stdout:'level: 88\n'};if(s.includes('df -k /data'))return {exitCode:0,stdout:'Filesystem 1K-blocks Used Available Use% Mounted\n/data 1000 500 500 50% /data\n'};if(s.includes('development_settings_enabled'))return {exitCode:0,stdout:'1\n'};if(s.includes('adb_enabled'))return {exitCode:0,stdout:'1\n'};return {exitCode:1,stdout:''};};const r=new AsgardRuntime({root,commandRunner:runner});const out=await r.action({action:'atreus-doctor'});assert.equal(out.health.ok,true);assert.equal(out.health.batteryLevel,88);}finally{await rm(root,{recursive:true,force:true});}});
test('Atreus only changes allowlisted developer option after approval',async()=>{const root=await mkdtemp(join(tmpdir(),'asgard-'));try{const calls=[];const r=new AsgardRuntime({root,commandRunner:async c=>{calls.push(c.argv);return {exitCode:0,stdout:''};}});const denied=await r.action({action:'atreus-set-developer-option',payload:{name:'window_animation_scale',value:0,approved:false}});assert.equal(denied.reason,'APPROVAL_REQUIRED');const ok=await r.action({action:'atreus-set-developer-option',payload:{name:'window_animation_scale',value:0,approved:true}});assert.equal(ok.executed,true);assert.deepEqual(calls[0],['adb','shell','settings','put','global','window_animation_scale','0']);}finally{await rm(root,{recursive:true,force:true});}});
test('ASGARD state persists core ledgers',async()=>{const root=await mkdtemp(join(tmpdir(),'asgard-'));try{const r=new AsgardRuntime({root});await r.action({action:'invoke-agent',payload:{name:'Floki'}});await r.action({action:'loki-ingest',payload:{title:'x'}});await r.action({action:'kratos-secret-register',payload:{id:'g',provider:'github',envRef:'GITHUB_TOKEN'}});await r.action({action:'floki-record',payload:{category:'AI',item:'x'}});const s=await r.action({action:'state-save'});assert.ok(s.version>=15);const r2=new AsgardRuntime({root});const l=await r2.action({action:'state-load'});assert.equal(l.activeAgent,'floki');assert.equal((await r2.action({action:'kratos-secret-list'})).length,1);}finally{await rm(root,{recursive:true,force:true});}});
