import test from 'node:test';
import assert from 'node:assert/strict';
import {
  ActionSupplyChainAuditor, LandingPolicyEngine, AgentReliabilityAuditor, AiArtifactDiffGate,
  McpBehaviorGradeGate, KnowledgeSubstrate, WorkItemSessionStore, CanonicalAgentSyncPlanner,
  ReactNativeSpecialistRouter, DemoContractValidator, DeclarativeAgentContractValidator, LogEvidenceVerifier
} from '../src/assurance/assurance-architecture.mjs';

test('Action audit rejects mutable third-party refs',()=>{const r=new ActionSupplyChainAuditor().audit({workflow:'steps:\n - uses: vendor/agent@v1'});assert.equal(r.passed,false);assert.ok(r.findings.some(x=>x.code==='ACT002'));});
test('Action audit accepts pinned third-party refs',()=>{const r=new ActionSupplyChainAuditor().audit({workflow:`steps:\n - uses: vendor/agent@${'a'.repeat(40)}`});assert.equal(r.passed,true);});
test('Action audit catches pull_request_target head checkout',()=>{const r=new ActionSupplyChainAuditor().audit({workflow:'on:\n  pull_request_target:\nsteps:\n - uses: actions/checkout@v4\n   with:\n     ref: ${{ github.event.pull_request.head.sha }}'});assert.ok(r.findings.some(x=>x.code==='ACT005'));});
test('Landing gate parks sensitive paths',()=>{const r=new LandingPolicyEngine().evaluate({policy:{ackPaths:['.github/workflows']},changes:[{path:'.github/workflows/x.yml'}]});assert.equal(r.decision,'PARK');});
test('Landing policy cannot be loosened',()=>{const r=new LandingPolicyEngine().compare({base:{requiredChecks:['test'],maxAgents:4,minMcpGrade:'B',requirePinnedActions:true},candidate:{requiredChecks:[],maxAgents:8,minMcpGrade:'D',requirePinnedActions:false}});assert.equal(r.allowed,false);assert.ok(r.violations.length>=4);});
test('Lane violation blocks landing',()=>{const r=new LandingPolicyEngine().evaluate({policy:{lanes:[{id:'api',paths:['src/api']}]},changes:[{path:'src/ui/x.js',laneId:'api'}]});assert.equal(r.decision,'BLOCK');});
test('Reliability audit catches unbounded broad agent',()=>{const r=new AgentReliabilityAuditor().audit({description:'short',tools:['shell'],parameters:{x:{}},networkAllowlist:['*']});assert.equal(r.ready,false);assert.ok(r.findings.length>=5);});
test('Reliability audit passes bounded spec',()=>{const r=new AgentReliabilityAuditor().audit({description:'Bounded repository analysis agent with explicit scope',tools:['read'],timeoutMs:1000,retries:1,maxIterations:5,observability:true,networkAllowlist:['api.github.com'],parameters:{q:{type:'string'}},budget:2});assert.equal(r.ready,true);});
test('AI artifact gate holds permission widening',()=>{const r=new AiArtifactDiffGate().diff({before:[{type:'mcp',id:'x',permissions:['read']}],after:[{type:'mcp',id:'x',permissions:['read','write']}]});assert.equal(r.decision,'HOLD');});
test('AI artifact gate passes identical surface',()=>{const x=[{type:'skill',id:'a',permissions:['read'],model:'m'}];const r=new AiArtifactDiffGate().diff({before:x,after:x});assert.equal(r.decision,'PASS');});
test('MCP grade gate rejects D below B',()=>{const r=new McpBehaviorGradeGate().evaluate({targets:[{id:'x',grade:'D',evidenceHash:'e'}],minGrade:'B'});assert.equal(r.passed,false);});
test('MCP grade gate accepts pinned A target',()=>{const r=new McpBehaviorGradeGate().evaluate({targets:[{id:'x',grade:'A',evidenceHash:'e',sourceType:'git',commitSha:'a'.repeat(40)}]});assert.equal(r.passed,true);});
test('Knowledge substrate enforces CAS',()=>{const k=new KnowledgeSubstrate();k.docsetUpsert({id:'docs',prefix:'docs',roles:{writer:['rw']}});k.identityUpsert({id:'a',roles:['writer']});const a=k.write({identity:'a',path:'docs/x.md',content:'a'});assert.throws(()=>k.write({identity:'a',path:'docs/x.md',content:'b',expectedHash:'bad'}),/CAS_MISMATCH/);const b=k.write({identity:'a',path:'docs/x.md',content:'b',expectedHash:a.record.hash});assert.equal(b.record.revision,2);});
test('Knowledge substrate routes protected writes to approval',()=>{const k=new KnowledgeSubstrate();k.docsetUpsert({id:'ops',prefix:'ops',roles:{writer:['rw'],approver:['approve']},requiresApproval:[{path:'ops/policy.md'}]});k.identityUpsert({id:'w',roles:['writer']});k.identityUpsert({id:'p',roles:['approver']});const r=k.write({identity:'w',path:'ops/policy.md',content:'x'});assert.equal(r.pending,true);const a=k.approve({identity:'p',requestId:r.request.id});assert.equal(a.record.revision,1);});
test('Work item session does not resume unresolved task',()=>{const s=new WorkItemSessionStore();s.save({provider:'claude',workItem:'pr-1',workflow:'review',sessionId:'s1',unresolvedTasks:true});assert.equal(s.resume({provider:'claude',workItem:'pr-1',workflow:'review'}).resumable,false);});
test('Work item session is isolated by scope',()=>{const s=new WorkItemSessionStore();s.save({provider:'claude',workItem:'pr-1',workflow:'review',sessionId:'s1'});assert.equal(s.resume({provider:'claude',workItem:'pr-2',workflow:'review'}).resumable,false);});
test('Agent sync plans provider projections from canonical source',()=>{const r=new CanonicalAgentSyncPlanner().plan({agents:[{id:'reviewer',description:'x'}],providers:['claude','codex']});assert.equal(r.projections.length,2);assert.equal(r.canonicalRoot,'.agents');});
test('React Native router selects narrow specialists',()=>{const r=new ReactNativeSpecialistRouter().route({changedFiles:['android/app/build.gradle','src/billing.ts'],maxAgents:3});assert.ok(r.selected.includes('build'));assert.ok(r.selected.includes('payments'));assert.ok(r.selected.length<=3);});
test('Demo contract rejects unsupported steps',()=>{const r=new DemoContractValidator().validate({scenario:{id:'x',steps:[{type:'magic'}]}});assert.equal(r.valid,false);});
test('Demo contract accepts deterministic browser scenario',()=>{const r=new DemoContractValidator().validate({scenario:{id:'x',steps:[{type:'goto'},{type:'click'}]}});assert.equal(r.valid,true);assert.equal(r.deterministic,true);});
test('Log evidence hash does not claim semantic authenticity',()=>{const r=new LogEvidenceVerifier().verify({content:'abc'});assert.equal(r.authenticityClaimed,false);assert.equal(r.sha256.length,64);});

test('Declarative agent contract rejects wildcards and raw secrets',()=>{const r=new DeclarativeAgentContractValidator().validate({id:'a',trigger:{type:'issue'},permissions:{hosts:['*'],executables:['*'],paths:['/']},secrets:['sk-abc'],budget:{},maxSteps:0,timeoutMs:0,tools:['shell']});assert.equal(r.valid,false);assert.ok(r.findings.some(x=>x.code==='DAC006'));});
test('Declarative agent contract accepts bounded permissions and secret refs',()=>{const r=new DeclarativeAgentContractValidator().validate({id:'a',trigger:{type:'issue'},permissions:{hosts:['api.github.com'],executables:['git'],paths:['src']},secrets:[{ref:'GITHUB_TOKEN',scope:'repo'}],budget:{maxCost:2},maxSteps:20,timeoutMs:60000,tools:['git']});assert.equal(r.valid,true);});
