import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import {
  SkillCatalog, SkillEvalHarness, McpSecurityGateway, A2ARouter, StatefulAgentKernel,
  SandboxWarmPool, TraceStore, CodeGraph, AndroidFeedbackLoop, AutomationPieceRegistry
} from '../src/ecosystem/ecosystem-architecture.mjs';
import { EcosystemRuntime } from '../src/ecosystem/ecosystem-runtime.mjs';

test('skill catalog exposes progressive disclosure only',()=>{const c=new SkillCatalog();c.upsert({id:'a',name:'android-build',description:'Build Android apps',instructions:'secret long body',location:'x/SKILL.md'});assert.deepEqual(c.progressiveCatalog(),[{id:'a',name:'android-build',description:'Build Android apps',location:'x/SKILL.md'}]);assert.equal(c.activate('a').instructions,'secret long body');});
test('skill catalog deduplicates near-identical skills',()=>{const c=new SkillCatalog({duplicateThreshold:.6});c.upsert({id:'a',name:'mcp-gateway',description:'Secure MCP gateway OAuth tools routing',tools:['call','list'],verified:true,tests:20});c.upsert({id:'b',name:'gateway-mcp',description:'MCP gateway secure tool routing with OAuth',tools:['call','list']});const g=c.deduplicate();assert.equal(g[0].size,2);assert.equal(g[0].canonical,'a');});
test('skill eval measures lift and tool assertions',()=>{const h=new SkillEvalHarness();const r=h.compare({skillId:'x',minLift:.1,toolAssertions:[{tool:'build'}],trials:[{without:{score:.4,latencyMs:100},with:{score:.8,latencyMs:120,toolCalls:['build']}}]});assert.equal(r.passed,true);assert.ok(r.meanLift>.39);});
test('gateway blocks loopback by default',()=>{const g=new McpSecurityGateway();assert.throws(()=>g.register({id:'x',url:'http://127.0.0.1:3000',tools:['a']}),/blocked/);});
test('gateway rejects tool collisions',()=>{const g=new McpSecurityGateway({allowPrivate:true});g.register({id:'a',url:'https://a.example',tools:['same']});assert.throws(()=>g.register({id:'b',url:'https://b.example',tools:['same']}),/collision/);});
test('gateway blocks secret-like tool arguments',()=>{const g=new McpSecurityGateway();g.register({id:'a',url:'https://a.example',tools:['x']});const r=g.authorize({tool:'x',arguments:{token:'ghp_123456789012345678901234567890'}});assert.equal(r.allowed,false);assert.equal(r.reason,'SECRET_DETECTED');});
test('gateway routes enabled tools',()=>{const g=new McpSecurityGateway();g.register({id:'a',url:'https://a.example',tools:['x']});assert.equal(g.route('x').serverId,'a');});
test('A2A router prefers trust and latency',()=>{const r=new A2ARouter();r.register({id:'a',capabilities:['code'],trust:.9,latencyMs:50,cost:2});r.register({id:'b',capabilities:['code'],trust:.6,latencyMs:500,cost:1});assert.equal(r.route({capability:'code'}).id,'a');});
test('stateful agent pause creates checkpoint',()=>{const k=new StatefulAgentKernel();const s=k.create({id:'s',agent:'builder',state:{x:1}});k.patch(s.id,{x:2});const cp=k.pause(s.id);assert.equal(cp.state.x,2);assert.equal(k.get(s.id).status,'PAUSED');});
test('stateful agent cannot patch while paused',()=>{const k=new StatefulAgentKernel();k.create({id:'s',agent:'x'});k.pause('s');assert.throws(()=>k.patch('s',{a:1}),/not running/);});
test('stateful agent handoff captures revision',()=>{const k=new StatefulAgentKernel();k.create({id:'s',agent:'lead'});k.patch('s',{a:1});assert.equal(k.handoff('s',{to:'qa',task:'verify'}).revision,1);});
test('sandbox warm pool claim and release',()=>{const p=new SandboxWarmPool();p.template({id:'t',network:'none'});p.prewarm('t',2);const x=p.claim('t','job');assert.equal(x.status,'CLAIMED');assert.equal(p.release(x.id).status,'WARM');});
test('sandbox reaps expired warm instances',()=>{const p=new SandboxWarmPool();p.template({id:'t',ttlMs:1000});const [x]=p.prewarm('t',1);assert.deepEqual(p.reap(x.expiresAt+1),[x.id]);});
test('trace store aggregates tool success cost tokens',()=>{const t=new TraceStore();const {id}=t.startTrace({name:'run'});t.span(id,{name:'a',kind:'tool',status:'OK',cost:1,tokens:10});t.span(id,{name:'b',kind:'tool',status:'ERROR',cost:2,tokens:20});const s=t.end(id);assert.equal(s.toolSuccessRate,.5);assert.equal(s.cost,3);assert.equal(s.tokens,30);});
test('code graph computes reverse impact',()=>{const g=new CodeGraph();for(const id of ['a','b','c'])g.addSymbol({id});g.link('b','a');g.link('c','b');assert.deepEqual(g.impact('a',{depth:2}).map(x=>x.id),['b','c']);});
test('code graph finds unreferenced non-exports',()=>{const g=new CodeGraph();g.addSymbol({id:'a'});g.addSymbol({id:'b',exported:true});assert.deepEqual(g.dead(),['a']);});
test('android refs expire after new snapshot',()=>{const d=new AndroidFeedbackLoop();d.open({id:'s'});const a=d.snapshot('s',[{role:'button'}]);const b=d.snapshot('s',[{role:'button'}]);assert.throws(()=>d.act('s',{ref:'@e1',action:'press',epoch:a.epoch}),/STALE/);assert.equal(d.act('s',{ref:'@e1',action:'press',epoch:b.epoch}).action,'press');});
test('android evidence is retained',()=>{const d=new AndroidFeedbackLoop();d.open({id:'s'});d.evidence('s',{type:'screenshot',path:'a.png'});assert.equal(d.get('s').evidence.length,1);});
test('automation piece validates structured input',()=>{const r=new AutomationPieceRegistry();r.register({id:'mail',inputSchema:{type:'object',required:['to'],properties:{to:{type:'string'}}},actions:['send']});assert.equal(r.validate('mail',{to:'a'}).valid,true);assert.equal(r.validate('mail',{}).valid,false);});
test('automation piece enforces approval',()=>{const r=new AutomationPieceRegistry();r.register({id:'deploy',inputSchema:{type:'object'},actions:['run'],requiresApproval:true});assert.equal(r.plan('deploy',{action:'run',input:{}}).reason,'APPROVAL_REQUIRED');assert.equal(r.plan('deploy',{action:'run',input:{},approved:true}).executable,true);});
test('runtime persists catalog/gateway/a2a',async()=>{const root=await mkdtemp(join(tmpdir(),'omega-v14-'));try{const r=new EcosystemRuntime({root});await r.action({action:'skill-upsert',payload:{id:'s',name:'x-skill',description:'does x'}});await r.action({action:'mcp-register',payload:{id:'m',url:'https://m.example',tools:['x']}});await r.action({action:'a2a-register',payload:{id:'a',capabilities:['x']}});const saved=await r.action({action:'state-save'});assert.deepEqual(saved.counts,{skills:1,mcp:1,a2a:1});const r2=new EcosystemRuntime({root});const loaded=await r2.action({action:'state-load'});assert.deepEqual(loaded.counts,{skills:1,mcp:1,a2a:1});}finally{await rm(root,{recursive:true,force:true});}});
test('runtime executes allowlisted agent-device command through runner',async()=>{const root=await mkdtemp(join(tmpdir(),'omega-v14-ad-'));try{const calls=[];const r=new EcosystemRuntime({root,commandRunner:async c=>{calls.push(c);return {exitCode:0,stdout:'ok',stderr:''};}});const out=await r.action({action:'android-live',payload:{command:'snapshot',args:['-i']}});assert.equal(out.available,true);assert.deepEqual(calls[0].argv,['agent-device','snapshot','-i']);}finally{await rm(root,{recursive:true,force:true});}});
test('runtime rejects arbitrary agent-device subcommand',async()=>{const root=await mkdtemp(join(tmpdir(),'omega-v14-ad2-'));try{const r=new EcosystemRuntime({root,commandRunner:async()=>({exitCode:0})});await assert.rejects(()=>r.action({action:'android-live',payload:{command:'shell'}}),/Unsupported/);}finally{await rm(root,{recursive:true,force:true});}});
test('runtime can invoke external skills-ref validator',async()=>{const root=await mkdtemp(join(tmpdir(),'omega-v14-skill-'));try{const r=new EcosystemRuntime({root,commandRunner:async c=>({exitCode:c.argv[0]==='skills-ref'?0:1,stdout:'valid',stderr:''})});const out=await r.action({action:'skill-validate-external',payload:{path:'skills/x'}});assert.equal(out.available,true);}finally{await rm(root,{recursive:true,force:true});}});
