import test from 'node:test';
import assert from 'node:assert/strict';
import { createHash, createHmac } from 'node:crypto';
import { mkdtemp, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { ElevenLabsMediaRuntimeV25 } from '../src/media/elevenlabs-v25-runtime.mjs';
function jr(v,s=200){return new Response(s===204?null:JSON.stringify(v),{status:s,headers:{'content-type':'application/json'}});}
async function make(fetchImpl,env={ELEVENLABS_API_KEY:'test-api-key'}){const root=await mkdtemp(join(tmpdir(),'omega-v25-'));return {root,rt:new ElevenLabsMediaRuntimeV25({root,env,fetchImpl,now:()=>new Date('2026-10-06T12:00:00Z')})};}
function jwt(key,extra={}){const now=Math.floor(new Date('2026-10-06T12:00:00Z').getTime()/1000),h=Buffer.from(JSON.stringify({alg:'HS256',typ:'JWT'})).toString('base64url'),p=Buffer.from(JSON.stringify({iss:'https://api.elevenlabs.io/convai/speech-engine',sub:'convai_speech_engine_upstream',nbf:now-1,exp:now+60,...extra})).toString('base64url'),secret=createHash('sha256').update(key).digest(),sig=createHmac('sha256',secret).update(h+'.'+p).digest('base64url');return h+'.'+p+'.'+sig;}
test('valid Speech Engine JWT',async()=>{const {rt}=await make(async()=>jr({}));const r=await rt.action({action:'speech-engine-verify-jwt',payload:{token:jwt('test-api-key')}});assert.equal(r.valid,true);assert.equal(r.rawTokenPersisted,false);});
test('bad Speech Engine JWT signature rejected',async()=>{const {rt}=await make(async()=>jr({}));await assert.rejects(()=>rt.action({action:'speech-engine-verify-jwt',payload:{token:jwt('wrong')}}),/signature/);});
test('event guard cancels and drops stale output',async()=>{const {rt}=await make(async()=>jr({}));let r=await rt.action({action:'speech-engine-event-guard',payload:{sessionId:'s',event:{type:'user_transcript',event_id:1}}});assert.equal(r.cancelInFlight,false);r=await rt.action({action:'speech-engine-event-guard',payload:{sessionId:'s',event:{type:'user_transcript',event_id:2}}});assert.equal(r.cancelInFlight,true);r=await rt.action({action:'speech-engine-event-guard',payload:{sessionId:'s',event:{type:'agent_response',event_id:1}}});assert.equal(r.reason,'STALE_EVENT_ID');});
test('speech engine list bounds page size',async()=>{let url;const {rt}=await make(async u=>{url=String(u);return jr({items:[]});});await rt.action({action:'speech-engine-list',payload:{pageSize:100,cursor:'n'}});assert.match(url,/page_size=100/);await assert.rejects(()=>rt.action({action:'speech-engine-list',payload:{pageSize:101}}),/1\.\.100/);});
test('speech engine update uses PATCH and approval',async()=>{let method;const {rt}=await make(async(u,o)=>{method=o.method;return jr({id:'seng_1'});});await assert.rejects(()=>rt.action({action:'speech-engine-update',payload:{speechEngineId:'seng_1'}}),/approved=true/);await rt.action({action:'speech-engine-update',payload:{approved:true,speechEngineId:'seng_1',name:'x'}});assert.equal(method,'PATCH');});
test('speech engine delete requires destructive ack',async()=>{const {rt}=await make(async()=>jr(null,204));await assert.rejects(()=>rt.action({action:'speech-engine-delete',payload:{approved:true,speechEngineId:'seng_1'}}),/destructiveAck/);const r=await rt.action({action:'speech-engine-delete',payload:{approved:true,destructiveAck:true,speechEngineId:'seng_1'}});assert.equal(r.deleted,true);});
test('music detailed parses multipart',async()=>{const b='xYz',meta=JSON.stringify({song_metadata:{title:'x'}}),body=Buffer.concat([Buffer.from('--'+b+'\r\nContent-Type: application/json\r\n\r\n'+meta+'\r\n--'+b+'\r\nContent-Type: audio/mpeg\r\n\r\n'),Buffer.from('AUDIO'),Buffer.from('\r\n--'+b+'--\r\n')]);const {root,rt}=await make(async()=>new Response(body,{status:200,headers:{'content-type':'multipart/mixed; boundary='+b}}));const r=await rt.action({action:'music-compose-detailed',payload:{approved:true,prompt:'original',outputPath:'x.mp3'}});assert.equal(r.metadata.song_metadata.title,'x');assert.equal((await readFile(join(root,'x.mp3'))).toString(),'AUDIO');});
test('dialogue timestamps extracts audio',async()=>{const {root,rt}=await make(async()=>jr({audio_base_64:Buffer.from('MP3').toString('base64'),alignment:{characters:['a']}}));const r=await rt.action({action:'dialogue-with-timestamps',payload:{approved:true,inputs:[{text:'hi',voiceId:'v1'}],outputPath:'d.mp3'}});assert.equal((await readFile(join(root,'d.mp3'))).toString(),'MP3');assert.equal('audio_base_64' in r,false);});
test('SFX enforces 0.5 second minimum',async()=>{const {rt}=await make(async()=>new Response(Buffer.from('A'),{status:200}));await assert.rejects(()=>rt.action({action:'sound-effect-generate',payload:{approved:true,text:'hit',durationSeconds:.49}}),/0\.5\.\.30/);});
test('SFX enforces prompt influence',async()=>{const {rt}=await make(async()=>new Response(Buffer.from('A'),{status:200}));await assert.rejects(()=>rt.action({action:'sound-effect-generate',payload:{approved:true,text:'hit',promptInfluence:2}}),/0\.\.1/);});
test('dubbing project requires billing ack',async()=>{const {rt}=await make(async()=>jr({project_id:'p'}));await assert.rejects(()=>rt.action({action:'dubbing-project-create',payload:{approved:true,sourceUrl:'https://example.test/a'}}),/billingAck/);});
test('dubbing language requires billing ack',async()=>{const {rt}=await make(async()=>jr({language_id:'l'}));await assert.rejects(()=>rt.action({action:'dubbing-language-create',payload:{approved:true,projectId:'p',targetLanguage:'pl'}}),/billingAck/);});
test('upstream contract exposes JWT semantics',async()=>{const {rt}=await make(async()=>jr({}));const r=await rt.action({action:'speech-engine-upstream-contract'});assert.equal(r.authentication.type,'JWT-HS256');assert.match(r.interruption,/event_id/);});
test('capabilities expose v25 operations',async()=>{const {rt}=await make(async()=>jr({}));const r=await rt.action({action:'capabilities'});assert.equal(r.hardeningVersion,25);assert.ok(r.operations.music.includes('compose-detailed'));});
